######################################################################################
#############   Aries ACA-Py ACC-Py Jupyter Playground Configuration   ###############
######################################################################################
############ This removes ngrok services
############ And uses a Dockerfile.agent.prod
############ This changes the startup script used see startup-prod.sh
############ You must define ACAPY_ENDPOINT in the .env file
############ This should be http://<somepublicip>:<exposed http port>
############ Where exposed http port is the HTTP PORT mapped to the machine
############ E.g. 4020:3020 would mean port is 4020
############ This port must be publically accessible for HTTP requests
############ You could of course turn this into a domain name instead
######################################################################################
version: "3"
services:
  ##### manufacturer1 Services #####
  # wallet-db
  # a postgres database where agent data will be persisted unless you run ./manage down
  # ./manage stop with stop the containers but persist the database volumes
  manufacturer1-wallet-db:
    image: postgres:11
    container_name: manufacturer1-wallet-db
    command: postgres -c listen_addresses='*'
    # env file defines
    env_file:
      - agents/manufacturer1/.env
    # This creates the data base tables if not present. See resources/init.sql #
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - manufacturer1-domain
    tty: true
  ### agent
  # This is manufacturer1's ACA-Py instance
  # See dockerfiles/Dockerfile.agent
  manufacturer1-agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.agent.prod
    env_file:
      - agents/manufacturer1/.env
    ## These map from ports defined in the .env file to unique ports on your machine
    ## YOUR_MACHINE:DOCKER_SERVICE
    ports:
      # HTTP_PORT
      - 4020:3020
      # ADMIN_PORT
      - 4021:3021
    depends_on:
      - manufacturer1-wallet-db
    networks:
      - manufacturer1-domain
  ### business-logic
  # This is where you will create notebooks to interact with your agent
  # This uses the aries-cloudcontroller pip package.
  # See dockerfiles/Dockerfile.controller
  # All business logic share a common set of code recipes to get you started
  manufacturer1-business-logic:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.controller
    env_file:
      - agents/manufacturer1/.env
    depends_on:
      - manufacturer1-agent
    networks:
      - manufacturer1-domain
    volumes:
      - ./agents/manufacturer1/notebooks:/workspace
      - ./recipes:/workspace/recipes
      - ./libs:/workspace/libs
    ports:
      # Jupyter Notebook port - always map from 8888 to any available port
      - 8889:8888
      # WEBHOOK_PORT
      - 4010:3010
  #########################################################################
  #### authority Services
  authority-wallet-db:
    image: postgres:11
    container_name: authority-wallet-db
    command: postgres -c listen_addresses='*'
    env_file:
      - agents/authority/.env
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - authority-domain
    tty: true
  authority-agent:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.agent.prod
    env_file:
      - agents/authority/.env
    ports:
      - 3020:3020
      - 3021:3021
    depends_on:
      - authority-wallet-db
    networks:
      - authority-domain
  authority-business-logic:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.controller
    env_file:
      - agents/authority/.env
    depends_on:
      - authority-agent
    networks:
      - authority-domain
    volumes:
      - ./agents/authority/notebooks:/workspace
      - ./recipes:/workspace/recipes
      - ./libs:/workspace/libs
    ports:
      - "8888:8888"
      - 3010:3010
#    #### ACTOR TEMPLATE SERVICES - Uncomment and edit as appropriate ######
#      template-wallet-db:
#        image: postgres:11
#        container_name: template-wallet-db
#        command: postgres -c listen_addresses='*'
#        # env file defines
#        env_file:
#          - agents/template/.env
#        volumes:
#          - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
#        networks:
#          - template-domain
#        tty: true
#      template-agent:
#        build:
#          context: .
#          dockerfile: dockerfiles/Dockerfile.agent
#        env_file:
#          - agents/template/.env
#        ports:
#          # HTTP_PORT
#          - <UNIQUE_PORT>:3020
#          # ADMIN_PORT
#          - <UNIQUE_PORT>:3021
#        depends_on:
#          - template-wallet-db
#        networks:
#          - template-domain
#      template-business-logic:
#        build:
#          context: .
#          dockerfile: dockerfiles/Dockerfile.controller
#        env_file:
#          - agents/template/.env
#        depends_on:
#          - template-agent
#        networks:
#          - template-domain
#        volumes:
#          - ./agents/template/notebooks:/workspace
#          - ./recipes:/workspace/recipes
#        ports:
#          - 8890:8888
#          # WEBHOOK_PORT
#          - <UNIQUE_PORT>:3010
##### UNCOMMENT FOR A TAILS SERVER ######
# Note - for revocation to work you will have to make additional changes to the env files
#  tails-server:
#    env_file:
#      - agents/authority/.env
#    build:
#      context: https://github.com/bcgov/indy-tails-server.git
#      dockerfile: docker/Dockerfile.tails-server
#    ports:
#      - 6543:6543
#    networks:
#      - demo-participant-domain
#      - hlgf-domain
#    command: >
#      tails-server
#        --host 0.0.0.0
#        --port 6543
#        --storage-path /tmp/tails-files
#        --log-level INFO
networks:
  authority-domain:
  manufacturer1-domain:
