FROM continuumio/miniconda3

ENV WORKSPACE /workspace

ARG jupyter_port
ENV env_jupyter_port=jupyter_port

# Setup workspace environment and get jupyterlab
RUN apt-get update && apt-get install -y gcc
RUN conda install -c conda-forge jupyterlab==3.0.11

WORKDIR ./

# Install the aries_cloudcontroller
ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Install Syft
ADD PySyft/packages/syft syft
RUN pip3 install syft

# Install submodule SyMPC (see SyMPC/docker-images/Dockerfile)
ADD SyMPC SyMPC
WORKDIR SyMPC
RUN pip3 install setuptools_scm
RUN pip3 install -r requirements.txt #&& pip3 install -r requirements.dev.txt
RUN pip3 install -e .

# Create jupyter notebook workspace
#RUN mkdir $WORKSPACE
WORKDIR $WORKSPACE

# Make the image start the jupyter notebook
COPY scripts/jupyter-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh", "$env_jupyter_port"]
ENTRYPOINT ["/entrypoint.sh", "8888"]